"""Added relationship btw Transaction and TransactionEvents Tables

Revision ID: 411f6914d021
Revises: e151c9ab6567
Create Date: 2026-09-11 16:38:03.196267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '411f6914d021'
down_revision: Union[str, Sequence[str], None] = 'e151c9ab6567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_event_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_transactions_transaction_event_id'), 'transactions', ['transaction_event_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'transaction_events', ['transaction_event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_transaction_event_id'), table_name='transactions')
    op.drop_column('transactions', 'transaction_event_id')
    # ### end Alembic commands ###
