"""Removed unique from user_id and idempotency_key rows in Idempotency_Key table and added a contrainst instead

Revision ID: 4f38dc649ea6
Revises: 8894e9189c13
Create Date: 2026-08-25 19:18:14.853596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4f38dc649ea6'
down_revision: Union[str, Sequence[str], None] = '8894e9189c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_idempotency_keys_idempotency_key'),
                  table_name='idempotency_keys')
    op.create_index(op.f('ix_idempotency_keys_idempotency_key'),
                    'idempotency_keys', ['idempotency_key'], unique=False)
    op.drop_index(op.f('ix_idempotency_keys_user_id'),
                  table_name='idempotency_keys')
    op.create_index(op.f('ix_idempotency_keys_user_id'),
                    'idempotency_keys', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_idempotency_key', 'idempotency_keys', [
                                'user_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_idempotency_key',
                       'idempotency_keys', type_='unique')
    op.drop_index(op.f('ix_idempotency_keys_user_id'),
                  table_name='idempotency_keys')
    op.create_index(op.f('ix_idempotency_keys_user_id'),
                    'idempotency_keys', ['user_id'], unique=True)
    op.drop_index(op.f('ix_idempotency_keys_idempotency_key'),
                  table_name='idempotency_keys')
    op.create_index(op.f('ix_idempotency_keys_idempotency_key'),
                    'idempotency_keys', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###
