"""Updated wallet and transaction relationship

Revision ID: 87bfa8bc8cca
Revises: b7f85510e76f
Create Date: 2026-08-24 16:42:54.437413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '87bfa8bc8cca'
down_revision: Union[str, Sequence[str], None] = 'b7f85510e76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
