"""Added idempotency_key table + relationship with users table

Revision ID: b2225b36e13f
Revises: 87bfa8bc8cca
Create Date: 2026-08-25 15:53:40.700093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b2225b36e13f'
down_revision: Union[str, Sequence[str], None] = '87bfa8bc8cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_keys', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.add_column('idempotency_keys', sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('idempotency_keys', sa.Column('recovery_point', sa.Enum('STARTED', 'FUNDS_RESERVED', 'OUTBOX_WRITTEN', 'PROVIDER_CALLED', 'COMPLETED', 'FAILED', name='recoverypoint'), nullable=False))
    op.add_column('idempotency_keys', sa.Column('request_params', sa.JSON(), nullable=True))
    op.add_column('idempotency_keys', sa.Column('response_code', sa.Integer(), nullable=True))
    op.add_column('idempotency_keys', sa.Column('response_body', sa.JSON(), nullable=True))
    op.add_column('idempotency_keys', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('idempotency_keys', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_idempotency_keys_idempotency_key'), 'idempotency_keys', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=True)
    op.create_foreign_key(None, 'idempotency_keys', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'idempotency_keys', type_='foreignkey')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_index(op.f('ix_idempotency_keys_idempotency_key'), table_name='idempotency_keys')
    op.drop_column('idempotency_keys', 'created_at')
    op.drop_column('idempotency_keys', 'locked_at')
    op.drop_column('idempotency_keys', 'response_body')
    op.drop_column('idempotency_keys', 'response_code')
    op.drop_column('idempotency_keys', 'request_params')
    op.drop_column('idempotency_keys', 'recovery_point')
    op.drop_column('idempotency_keys', 'idempotency_key')
    op.drop_column('idempotency_keys', 'user_id')
    # ### end Alembic commands ###
