"""Added sender and receiver wallet ids instead, updated transaction status and added transaction type. Modified the relationships in users and wallet tables

Revision ID: b7f85510e76f
Revises: 252dc6ca9b3a
Create Date: 2026-08-22 18:39:58.300367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b7f85510e76f'
down_revision: Union[str, Sequence[str], None] = '252dc6ca9b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_wallet_id', sa.Uuid(), nullable=True))
    op.add_column('transactions', sa.Column('receiver_wallet_id', sa.Uuid(), nullable=True))
    op.add_column('transactions', sa.Column('type', sa.Enum('TRANSFER', 'DEPOSIT', 'WITHDRAWAL', name='transactiontype'), nullable=False))
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_receiver_wallet_id'), 'transactions', ['receiver_wallet_id'], unique=False)
    op.create_index(op.f('ix_transactions_sender_wallet_id'), 'transactions', ['sender_wallet_id'], unique=False)
    op.drop_constraint(op.f('transactions_user_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'wallet', ['sender_wallet_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'wallet', ['receiver_wallet_id'], ['id'])
    op.drop_column('transactions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_user_id_fkey'), 'transactions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_transactions_sender_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_receiver_wallet_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.drop_column('transactions', 'type')
    op.drop_column('transactions', 'receiver_wallet_id')
    op.drop_column('transactions', 'sender_wallet_id')
    # ### end Alembic commands ###
