"""Fixed the relationship issue btw Transaction and TransactionEvents Tables

Revision ID: ca5392b0927c
Revises: 411f6914d021
Create Date: 2026-09-11 17:03:22.724419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ca5392b0927c'
down_revision: Union[str, Sequence[str], None] = '411f6914d021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_transaction_event_id'), table_name='transactions')
    op.drop_constraint(op.f('transactions_transaction_event_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'transaction_event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_event_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('transactions_transaction_event_id_fkey'), 'transactions', 'transaction_events', ['transaction_event_id'], ['id'])
    op.create_index(op.f('ix_transactions_transaction_event_id'), 'transactions', ['transaction_event_id'], unique=False)
    # ### end Alembic commands ###
