"""Fixed idempotency_key and user relationship issue

Revision ID: d4d4753b270d
Revises: 6f9d4d1a226e
Create Date: 2026-08-25 17:36:56.926384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd4d4753b270d'
down_revision: Union[str, Sequence[str], None] = '6f9d4d1a226e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
