"""Added TransactionEvent table

Revision ID: e151c9ab6567
Revises: 50e81c3cccba
Create Date: 2026-09-11 16:26:40.484880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e151c9ab6567'
down_revision: Union[str, Sequence[str], None] = '50e81c3cccba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactionevent')
    op.add_column('transaction_events', sa.Column('transaction_id', sa.Uuid(), nullable=False))
    op.add_column('transaction_events', sa.Column('from_status', sa.Enum('PENDING', 'FLAGGED', 'CLEARED', 'REJECTED', name='transactionstatus'), nullable=False))
    op.add_column('transaction_events', sa.Column('to_status', sa.Enum('PENDING', 'FLAGGED', 'CLEARED', 'REJECTED', name='transactionstatus'), nullable=False))
    op.add_column('transaction_events', sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('transaction_events', sa.Column('actor', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('transaction_events', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('transaction_events', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_transaction_events_transaction_id'), 'transaction_events', ['transaction_id'], unique=False)
    op.create_foreign_key(None, 'transaction_events', 'transactions', ['transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_events', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_events_transaction_id'), table_name='transaction_events')
    op.drop_column('transaction_events', 'updated_at')
    op.drop_column('transaction_events', 'created_at')
    op.drop_column('transaction_events', 'actor')
    op.drop_column('transaction_events', 'reason')
    op.drop_column('transaction_events', 'to_status')
    op.drop_column('transaction_events', 'from_status')
    op.drop_column('transaction_events', 'transaction_id')
    op.create_table('transactionevent',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('transactionevent_pkey'))
    )
    # ### end Alembic commands ###
