"""Added next_retry_at to transaction outbox

Revision ID: e565d2fad6aa
Revises: 4f38dc649ea6
Create Date: 2026-09-05 19:12:04.908091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e565d2fad6aa'
down_revision: Union[str, Sequence[str], None] = '4f38dc649ea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_outbox', sa.Column('next_retry_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_outbox', 'next_retry_at')
    # ### end Alembic commands ###
