"""Fixed relationship referencing between wallet and users models

Revision ID: f70ee552a67e
Revises: d21d8fffb5ee
Create Date: 2026-08-21 15:41:22.168010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f70ee552a67e'
down_revision: Union[str, Sequence[str], None] = 'd21d8fffb5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
